#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${GOOGLE_CLOUD_PROJECT:-}" ]]; then
  echo "GOOGLE_CLOUD_PROJECT is required"
  exit 1
fi

REGION="${GOOGLE_CLOUD_REGION:-asia-south1}"
SERVICE_NAME="${GO_TUTOR_SERVICE_NAME:-smart-study-buddy-go-tutor}"
MODEL="${GO_TUTOR_MODEL:-gemini-2.5-pro}"
PLAY_PACKAGE_NAME="${GOOGLE_PLAY_PACKAGE_NAME:-com.smartstudybuddy.app}"
ENABLE_RAG="${ENABLE_NCERT_RAG:-true}"
TOP_K="${NCERT_TOP_K:-4}"
INDEX_PATH="${NCERT_VECTOR_INDEX_PATH:-/app/content/index/ncert_embeddings.jsonl}"
INDEX_GCS_URI="${NCERT_VECTOR_INDEX_GCS_URI:-}"
INDEX_GCS_PUBLIC_URL="${NCERT_VECTOR_INDEX_GCS_PUBLIC_URL:-}"
IMAGE="gcr.io/${GOOGLE_CLOUD_PROJECT}/${SERVICE_NAME}:latest"
ALLOW_TIER_ENDPOINT="${ALLOW_TIER_ENDPOINT:-false}"

# Optional Secret Manager integration for production-safe deploys.
GENAI_SECRET="${GOOGLE_GENAI_API_KEY_SECRET:-}"
APPLE_SECRET_NAME="${APPLE_SHARED_SECRET_SECRET:-}"
FIREBASE_SECRET_NAME="${FIREBASE_WEB_API_KEY_SECRET:-}"
RTDN_SECRET_NAME="${GOOGLE_RTDN_BEARER_TOKEN_SECRET:-}"
APPLE_NOTIF_SECRET_NAME="${APPLE_SERVER_NOTIFICATIONS_BEARER_TOKEN_SECRET:-}"
RECONCILE_SECRET_NAME="${RECONCILE_BEARER_TOKEN_SECRET:-}"

if [[ -z "${GENAI_SECRET}" && -z "${GOOGLE_GENAI_API_KEY:-}" ]]; then
  echo "Set either GOOGLE_GENAI_API_KEY_SECRET (recommended) or GOOGLE_GENAI_API_KEY."
  exit 1
fi

echo "Building Go tutor image ${IMAGE}"
gcloud builds submit \
  --config infra/cloudbuild-go-tutor.yaml \
  --substitutions "_IMAGE=${IMAGE}" \
  .

echo "Deploying ${SERVICE_NAME} to Cloud Run"
DEPLOY_CMD=(
  gcloud run deploy "${SERVICE_NAME}"
  --image "${IMAGE}" \
  --region "${REGION}" \
  --platform managed \
  --allow-unauthenticated \
  --timeout=120 \
  --memory=512Mi \
  --set-env-vars "GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT},GO_TUTOR_MODEL=${MODEL},GOOGLE_PLAY_PACKAGE_NAME=${PLAY_PACKAGE_NAME},ENABLE_NCERT_RAG=${ENABLE_RAG},NCERT_TOP_K=${TOP_K},NCERT_VECTOR_INDEX_PATH=${INDEX_PATH},NCERT_VECTOR_INDEX_GCS_URI=${INDEX_GCS_URI},NCERT_VECTOR_INDEX_GCS_PUBLIC_URL=${INDEX_GCS_PUBLIC_URL},CONTENT_DIR=/app/content,ALLOW_TIER_ENDPOINT=${ALLOW_TIER_ENDPOINT}"
)

SECRET_BINDINGS=()

if [[ -n "${GENAI_SECRET}" ]]; then
  SECRET_BINDINGS+=("GOOGLE_GENAI_API_KEY=${GENAI_SECRET}:latest")
else
  DEPLOY_CMD+=(--update-env-vars "GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}")
fi

if [[ -n "${APPLE_SECRET_NAME}" ]]; then
  SECRET_BINDINGS+=("APPLE_SHARED_SECRET=${APPLE_SECRET_NAME}:latest")
elif [[ -n "${APPLE_SHARED_SECRET:-}" ]]; then
  DEPLOY_CMD+=(--update-env-vars "APPLE_SHARED_SECRET=${APPLE_SHARED_SECRET}")
fi

if [[ -n "${FIREBASE_SECRET_NAME}" ]]; then
  SECRET_BINDINGS+=("FIREBASE_WEB_API_KEY=${FIREBASE_SECRET_NAME}:latest")
elif [[ -n "${FIREBASE_WEB_API_KEY:-}" ]]; then
  DEPLOY_CMD+=(--update-env-vars "FIREBASE_WEB_API_KEY=${FIREBASE_WEB_API_KEY}")
fi

if [[ -n "${RTDN_SECRET_NAME}" ]]; then
  SECRET_BINDINGS+=("GOOGLE_RTDN_BEARER_TOKEN=${RTDN_SECRET_NAME}:latest")
elif [[ -n "${GOOGLE_RTDN_BEARER_TOKEN:-}" ]]; then
  DEPLOY_CMD+=(--update-env-vars "GOOGLE_RTDN_BEARER_TOKEN=${GOOGLE_RTDN_BEARER_TOKEN}")
fi

if [[ -n "${APPLE_NOTIF_SECRET_NAME}" ]]; then
  SECRET_BINDINGS+=("APPLE_SERVER_NOTIFICATIONS_BEARER_TOKEN=${APPLE_NOTIF_SECRET_NAME}:latest")
elif [[ -n "${APPLE_SERVER_NOTIFICATIONS_BEARER_TOKEN:-}" ]]; then
  DEPLOY_CMD+=(--update-env-vars "APPLE_SERVER_NOTIFICATIONS_BEARER_TOKEN=${APPLE_SERVER_NOTIFICATIONS_BEARER_TOKEN}")
fi

if [[ -n "${RECONCILE_SECRET_NAME}" ]]; then
  SECRET_BINDINGS+=("RECONCILE_BEARER_TOKEN=${RECONCILE_SECRET_NAME}:latest")
elif [[ -n "${RECONCILE_BEARER_TOKEN:-}" ]]; then
  DEPLOY_CMD+=(--update-env-vars "RECONCILE_BEARER_TOKEN=${RECONCILE_BEARER_TOKEN}")
fi

if [[ "${#SECRET_BINDINGS[@]}" -gt 0 ]]; then
  DEPLOY_CMD+=(--set-secrets "$(IFS=,; echo "${SECRET_BINDINGS[*]}")")
fi

"${DEPLOY_CMD[@]}"

echo "Go tutor deployed."
